- hosts: dev
  become: true
  become_user: root

  tasks:

  - name: install epel
    yum:
      name: ['epel-release']
      state: "installed"
  - name: install nginx
    yum:
      name: ['nginx']
      state: "installed"

  - name: disable selinux
    selinux:
      state: disabled
  - name: enable nginx
    service:
      name: "nginx"
      enabled: "yes"
  - name: start nginx
    service:
      name: "nginx"
      state: "restarted"
  - name: change in nginx configuration file
    template:
      src: "nginx.conf.j2"
      dest: "/etc/nginx/conf.d/default.conf"

  - name: change in apache configuration file
    template:
    src:  "apache.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"

  - name: install php5
    yum:
      name: ['php']
      state: "installed"
  - name: change in php configuration file
    template:
    src: "php.conf.j2"
    dest: "/usr/share/nginx/html/info.php"

